### ISSUE TITLE
ERROR: tools: run(): I/O operation on closed file

### ISSUE THREAD

**Issue by f3flight** [adobdin/timmy#51]
```
[root@fuel timmy]# ./timmy.py 
DEPRECATION WARNING: /etc/fuel/client/config.yaml exists and will be used as the source for settings. This behavior is deprecated. Please specify the path to your custom settings file in the FUELCLIENT_CUSTOM_SETTINGS environment variable.
Initializing node data: done
2016-07-29 12:22:10,038 ERROR: tools: run(): I/O operation on closed file
Traceback (most recent call last):
  File "/root/timmy/timmy/tools.py", line 100, in run
    result = self.target(**self.args)
  File "/root/timmy/timmy/nodes.py", line 245, in exec_cmd
    prefix=self.prefix)
  File "/root/timmy/timmy/tools.py", line 278, in ssh_node
    return launch_cmd(cmd, timeout, input=input, ok_codes=ok_codes)
  File "/root/timmy/timmy/tools.py", line 227, in launch_cmd
    outs, errs = p.communicate()
  File "/usr/lib64/python2.6/subprocess.py", line 732, in communicate
    stdout, stderr = self._communicate(input, endtime)
  File "/usr/lib64/python2.6/subprocess.py", line 1316, in _communicate
    stdout, stderr = self._communicate_with_poll(input, endtime)
  File "/usr/lib64/python2.6/subprocess.py", line 1374, in _communicate_with_poll
    register_and_append(self.stdout, select_POLLIN_POLLPRI)
  File "/usr/lib64/python2.6/subprocess.py", line 1353, in register_and_append
    poller.register(file_obj.fileno(), eventmask)
ValueError: I/O operation on closed file
2016-07-29 12:22:10,048 CRITICAL: tools: run_batch(): I/O operation on closed file, exiting
```

**Comment by f3flight** [comment]
Commented out the whole "except" section around line 227 in tools.py, now I get the real error:

```
[root@fuel timmy]# ./timmy.py
DEPRECATION WARNING: /etc/fuel/client/config.yaml exists and will be used as the source for settings. This behavior is deprecated. Please specify the path to your custom settings file in the FUELCLIENT_CUSTOM_SETTINGS environment variable.
Initializing node data: done
2016-07-29 12:43:33,876 ERROR: tools: run(): 'utf8' codec can't decode byte 0xec in position 1256: invalid continuation byte
Traceback (most recent call last):
  File "/root/timmy/timmy/tools.py", line 100, in run
    result = self.target(**self.args)
  File "/root/timmy/timmy/nodes.py", line 245, in exec_cmd
    prefix=self.prefix)
  File "/root/timmy/timmy/tools.py", line 278, in ssh_node
    return launch_cmd(cmd, timeout, input=input, ok_codes=ok_codes)
  File "/root/timmy/timmy/tools.py", line 218, in launch_cmd
    outs = outs.decode('utf-8')
  File "/usr/lib64/python2.6/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xec in position 1256: invalid continuation byte
2016-07-29 12:43:33,894 CRITICAL: tools: run_batch(): 'utf8' codec can't decode byte 0xec in position 1256: invalid continuation byte, exiting
```

**Comment by f3flight** [comment]
```
2016-07-29 12:24:51,532 INFO: tools: launch_cmd(): launching cmd input="$(cat | xxd -p)"; trap 'kill $pid' 15; trap 'kill $pid' 2; echo -n "$input" | xxd -r -p | OPENRC=/root/openrc IPTABLES_STR="iptables -nvL" timeout '15' bash -c 'nice -n 19 ionice -c 3 bash -s' < 'rq/scripts/blkid-o-list' &:; pid=$!; wait $!
2016-07-29 12:24:51,580 DEBUG: tools: launch_cmd(): ___command: input="$(cat | xxd -p)"; trap 'kill $pid' 15; trap 'kill $pid' 2; echo -n "$input" | xxd -r -p | OPENRC=/root/openrc IPTABLES_STR="iptables -nvL" timeout '15' bash -c 'nice -n 19 ionice -c 3 bash -s' < 'rq/scripts/blkid-o-list' &:; pid=$!; wait $!
_exit_code: 0
_____stdin: None
____stdout: device     fs_type label    mount point    UUID
-------------------------------------------------------------------------------
/dev/loop0 ext4             (in use)       60500a14-e06d-4eb1-b701-79a9523a9318
/dev/vda2  vfat             /boot/efi      A657-721E
/dev/vda3  ext4             /boot          9347b227-f6b9-402f-b2b7-e66f79b3d846
/dev/vda4  LVM2_member      (in use)       Jttdiv-EzRx-5aa6-rSxu-ciS8-E8cx-8m46BU
/dev/mapper/os-swap
           swap             <swap>         8fcb6b3d-504c-4fde-9379-afd70eec2de7
/dev/mapper/os-root
           ext4             /              90af64b9-1b4e-48e1-811d-79e37f65ec14
/dev/mapper/os-var
           ext4             /var           8b856d2d-bd83-47e2-bd88-6de11d684f3b
/dev/mapper/os-varlibdocker
           ext4             /var/lib/docker 18e36af5-57da-4f22-b72b-221083c45e76
/dev/mapper/os-varlog
           ext4             /var/log       249b9647-eef2-40af-9af5-ea412a480b5d
/dev/mapper/docker-253:3-262145-pool
           ext4             (in use)       60500a14-e06d-4eb1-b701-79a9523a9318
/dev/mapper/docker-253:3-262145-9c6e741b22c77bcb141fdc2e719b750d034289e2104ae8899bb6b0ebb1632605
           ext4             /var/lib/docker/devicemapper/mnt/9c6e741b22c77bcb141fdc2e719b750d034289e2104ae88C4 60500a14-e06d-4eb1-b701-79a9523a9318
/dev/mapper/docker-253:3-262145-d0a87b57a4dd7ff6eae6bf0b78b01c2c48ccd96b84de9d5a61da3322734c914e
           ext4             /var/lib/docker/devicemapper/mnt/d0a87b57a4dd7ff6eae6bf0b78b01c2c48ccd96b84de9d5>��: 60500a14-e06d-4eb1-b701-79a9523a9318
/dev/mapper/docker-253:3-262145-fb79db61cfb9dbf7be88f7dab013af5dc69a2c9793851af5e4d278dc32cbcf41
           ext4             /var/lib/docker/devicemapper/mnt/fb79db61cfb9dbf7be88f7dab013af5dc69a2c9793851af�J] 60500a14-e06d-4eb1-b701-79a9523a9318
/dev/mapper/docker-253:3-262145-cd42e937f76e58c6ca3fdc3732c119f5e678c76eaf0464c21bada7286752bd60
           ext4             /var/lib/docker/devicemapper/mnt/cd42e937f76e58c6ca3fdc3732c119f5e678c76eaf0464cA�- 60500a14-e06d-4eb1-b701-79a9523a9318
/dev/mapper/docker-253:3-262145-c11136fbecdf13c1c974c13b0159941cc969ab6353d85e4fe77607cf14d6b361
           ext4             /var/lib/docker/devicemapper/mnt/c11136fbecdf13c1c974c13b0159941cc969ab6353d85e4�;� 60500a14-e06d-4eb1-b701-79a9523a9318
/dev/mapper/docker-253:3-262145-efdf525e0b28d083633439047dbfee552d2b44d4290df38227380186a0cad301
           ext4             /var/lib/docker/devicemapper/mnt/efdf525e0b28d083633439047dbfee552d2b44d4290df38@�� 60500a14-e06d-4eb1-b701-79a9523a9318
/dev/mapper/docker-253:3-262145-38fa220dc5f3b53299f0a6a4f1cbfd2cb589630f2b03a63a152eec990a0070f1
           ext4             /var/lib/docker/devicemapper/mnt/38fa220dc5f3b53299f0a6a4f1cbfd2cb589630f2b03a63Af' 60500a14-e06d-4eb1-b701-79a9523a9318
/dev/mapper/docker-253:3-262145-b02b131fffc61af551efb0d23c45bdbc8a388c275f7a5a1d0b2362b05187c319
           ext4             /var/lib/docker/devicemapper/mnt/b02b131fffc61af551efb0d23c45bdbc8a388c275f7a5a1���1 60500a14-e06d-4eb1-b701-79a9523a9318
/dev/mapper/docker-253:3-262145-6b70121ff7b775ba3129a501ff5dd98ebd1d84643ca28c46a7e6a3367eebb75a
           ext4             /var/lib/docker/devicemapper/mnt/6b70121ff7b775ba3129a501ff5dd98ebd1d84643ca28c4A|�7 60500a14-e06d-4eb1-b701-79a9523a9318
/dev/mapper/docker-253:3-262145-9725dca704a12eadb6747b11cdf858f1e89d2b98a40ac1a089ae8134b6c13b1e
           ext4             /var/lib/docker/devicemapper/mnt/9725dca704a12eadb6747b11cdf858f1e89d2b98a40ac1a��
 60500a14-e06d-4eb1-b701-79a9523a9318
/dev/mapper/docker-253:3-262145-41428f6faef79668246da8560cc16a06b6c4013c7674f70abeda8e8661620722
 60500a14-e06d-4eb1-b701-79a9523a9318docker/devicemapper/mnt/41428f6faef79668246da8560cc16a06b6c4013c7674f70��J
```

Wonderful question marks

**Comment by f3flight** [comment]
Closing for now, issue mitigated
