### ISSUE TITLE
error on creating logs archive

### ISSUE THREAD

**Issue by adobdin** [adobdin/timmy#55]
```
2016-08-09 12:59:54,015 ERROR: tools: run(): 'utf8' codec can't decode byte 0x8b in position 1: invalid start byte
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/timmy/tools.py", line 100, in run
    result = self.target(**self.args)
  File "/usr/lib/python2.7/site-packages/timmy/nodes.py", line 274, in exec_simple_cmd
    prefix=self.prefix)
  File "/usr/lib/python2.7/site-packages/timmy/tools.py", line 267, in ssh_node
    return launch_cmd(cmd, timeout, input=input, ok_codes=ok_codes)
  File "/usr/lib/python2.7/site-packages/timmy/tools.py", line 220, in launch_cmd
    outs = outs.decode('utf-8')
  File "/usr/lib64/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)

```

**Comment by f3flight** [comment]
Which command? Probably the output contains garbage non-ascii and non-unicode chars, I had an identical issue with https://github.com/adobdin/timmy/blob/master/rq/scripts/blkid-o-list
