### ISSUE TITLE
Bug: traces with fuel module and simple json

### ISSUE THREAD

**Issue by adobdin** [adobdin/timmy#65]
`./timmy.py -lv -m fuel -j h.json --id 5
DEPRECATION WARNING: /etc/fuel/client/config.yaml exists and will be used as the source for settings. This behavior is deprecated. Please specify the path to your custom settings file in the FUELCLIENT_CUSTOM_SETTINGS environment variable.
2016-11-14 10:21:51,550 INFO: cli: main(): Using rqdir: /root/timmy/timmy_data/rq, rqfile: [{'default': True, 'file': '/root/timmy/timmy_data/rq/default.yaml'}]
2016-11-14 10:21:51,597 INFO: fuel: __init__(): Setup fuelclient instance
2016-11-14 10:21:51,608 INFO: tools: ssh_node(): cmd: timeout '30' ssh -T -oConnectTimeout=2 -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oLogLevel=error -oBatchMode=yes -oUser=root '10.20.12.5' 'OPENRC=/root/openrc LC_ALL="C" LANG="C"'  'nice -n 19 ionice -c 3 true'
2016-11-14 10:21:51,610 INFO: tools: ssh_node(): cmd: timeout '30' ssh -T -oConnectTimeout=2 -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oLogLevel=error -oBatchMode=yes -oUser=root '10.20.12.6' 'OPENRC=/root/openrc LC_ALL="C" LANG="C"'  'nice -n 19 ionice -c 3 true'
2016-11-14 10:21:51,622 INFO: tools: ssh_node(): cmd: OPENRC=/root/openrc LC_ALL="C" LANG="C" timeout '30' bash -c  'nice -n 19 ionice -c 3 true'
2016-11-14 10:21:51,829 INFO: tools: ssh_node(): cmd: timeout '30' ssh -T -oConnectTimeout=2 -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oLogLevel=error -oBatchMode=yes -oUser=root '10.20.12.5' 'OPENRC=/root/openrc LC_ALL="C" LANG="C"'  'nice -n 19 ionice -c 3 hiera roles'
2016-11-14 10:21:51,832 INFO: tools: ssh_node(): cmd: timeout '30' ssh -T -oConnectTimeout=2 -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oLogLevel=error -oBatchMode=yes -oUser=root '10.20.12.6' 'OPENRC=/root/openrc LC_ALL="C" LANG="C"'  'nice -n 19 ionice -c 3 hiera roles'
2016-11-14 10:21:52,108 INFO: tools: ssh_node(): cmd: timeout '30' ssh -T -oConnectTimeout=2 -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oLogLevel=error -oBatchMode=yes -oUser=root '10.20.12.6' 'OPENRC=/root/openrc LC_ALL="C" LANG="C"'  'nice -n 19 ionice -c 3 which lsb_release'
2016-11-14 10:21:52,111 INFO: tools: ssh_node(): cmd: timeout '30' ssh -T -oConnectTimeout=2 -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oLogLevel=error -oBatchMode=yes -oUser=root '10.20.12.5' 'OPENRC=/root/openrc LC_ALL="C" LANG="C"'  'nice -n 19 ionice -c 3 which lsb_release'
2016-11-14 10:21:52,312 INFO: tools: ssh_node(): cmd: OPENRC=/root/openrc LC_ALL="C" LANG="C" timeout '30' bash -c  'nice -n 19 ionice -c 3 python -c '"'"'import yaml; a = yaml.load(open("/etc/astute.yaml").read()); print a["cluster"]["id"]'"'"''
2016-11-14 10:21:52,314 INFO: tools: ssh_node(): cmd: timeout '30' ssh -T -oConnectTimeout=2 -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oLogLevel=error -oBatchMode=yes -oUser=root '10.20.12.5' 'OPENRC=/root/openrc LC_ALL="C" LANG="C"'  'nice -n 19 ionice -c 3 python -c '"'"'import yaml; a = yaml.load(open("/etc/astute.yaml").read()); print a["cluster"]["id"]'"'"''
2016-11-14 10:21:52,850 INFO: fuel: get_release_fuel_client(): getting release via fuelclient
2016-11-14 10:21:53,094 INFO: fuel: set_nodes_release(): node-3-10.20.12.5: release: n/a
2016-11-14 10:21:53,094 INFO: fuel: set_nodes_release(): node-4-10.20.12.6: release: 7.0
2016-11-14 10:21:53,094 INFO: fuel: set_nodes_release(): fuel: release: 7.0
Initializing node data: done
2016-11-14 10:21:53,107 CRITICAL: tools: collect_results(): exception in subprocess, pid: 29984, details:
2016-11-14 10:21:53,107 CRITICAL: tools: collect_results(): ____Traceback (most recent call last):
2016-11-14 10:21:53,107 CRITICAL: tools: collect_results(): ____  File "/root/timmy/timmy/tools.py", line 141, in run
2016-11-14 10:21:53,107 CRITICAL: tools: collect_results(): ____    result = self.target(**self.args)
2016-11-14 10:21:53,107 CRITICAL: tools: collect_results(): ____  File "/root/timmy/timmy/nodes.py", line 410, in logs_populate
2016-11-14 10:21:53,107 CRITICAL: tools: collect_results(): ____    self.log_item_manipulate(item)
2016-11-14 10:21:53,107 CRITICAL: tools: collect_results(): ____  File "/root/timmy/timmy/modules/fuel.py", line 189, in log_item_manipulate
2016-11-14 10:21:53,107 CRITICAL: tools: collect_results(): ____    ipd = os.path.join(remote_dir, n)
2016-11-14 10:21:53,108 CRITICAL: tools: collect_results(): ____  File "/usr/lib64/python2.6/posixpath.py", line 65, in join
2016-11-14 10:21:53,108 CRITICAL: tools: collect_results(): ____    if b.startswith('/'):
2016-11-14 10:21:53,108 CRITICAL: tools: collect_results(): ____AttributeError: 'NoneType' object has no attribute 'startswith'
2016-11-14 10:21:53,108 INFO: tools: cleanup(): cleaning up running subprocesses
[root@fuel timmy]# echo $?
109
`

`cat h.json 
[
    {
        "ip": "10.20.12.6",
        "cluster": 1,
        "id": 4
    },
    {
        "ip": "10.20.12.5", 
        "id": 3
    }
]
`

**Comment by adobdin** [comment]
Fix: https://review.openstack.org/#/c/397153
